// Mock restaurant + products for testing checkout flow without backend.
// Used as a fallback so the user always has data to add to cart.

export const MOCK_RESTAURANT_ID = "burguer-master";

export const mockRestaurant = {
  id: MOCK_RESTAURANT_ID,
  nome_fantasia: "Burguer Master",
  categoria: "Hambúrgueres",
  categorias: [{ id: 999, nome: "Hambúrgueres" }],
  logotipo: null as string | null,
  capa: null as string | null,
  is_open: true,
  nota_avaliacao: 4.8,
  tempo_entrega_minutos: 35,
  valor_frete: 6.9,
  pedido_minimo: 25.0,
};

export const mockProdutos = [
  {
    id: "bm-1",
    nome: "Master Cheeseburger",
    descricao: "Pão brioche, blend 180g, queijo cheddar duplo, picles e molho da casa.",
    preco: 32.9,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-2",
    nome: "Bacon Lover",
    descricao: "Blend 180g, bacon crocante, cebola caramelizada e cheddar.",
    preco: 38.5,
    em_promocao: true,
    preco_original: 42.0,
    preco_promocional: 35.9,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-3",
    nome: "Veggie Master",
    descricao: "Hambúrguer de grão-de-bico, alface, tomate e maionese vegana.",
    preco: 29.9,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-4",
    nome: "Batata Frita Crocante (G)",
    descricao: "Porção generosa de batatas crocantes com sal marinho.",
    preco: 18.0,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-5",
    nome: "Onion Rings",
    descricao: "Anéis de cebola empanados e crocantes com molho barbecue.",
    preco: 16.5,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-6",
    nome: "Refrigerante Lata 350ml",
    descricao: "Coca-Cola, Guaraná ou Sprite gelados.",
    preco: 7.5,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-7",
    nome: "Milk Shake Chocolate 400ml",
    descricao: "Cremoso milk shake artesanal com calda de chocolate belga.",
    preco: 19.9,
    em_promocao: false,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
  {
    id: "bm-8",
    nome: "Combo Master Duplo",
    descricao: "Master Cheeseburger + Batata G + Refrigerante.",
    preco: 54.9,
    em_promocao: true,
    preco_original: 62.0,
    preco_promocional: 49.9,
    disponivel: true,
    imagem: null,
    restaurante_id: MOCK_RESTAURANT_ID,
  },
];
